GH-244 - Extensible source support
adobe/aem-sidekick pull request #245
Opened 2024-09-06 19:45 UTC by auniverseaway

## Description
* Provides ability to let project spec a sourceFormat object
* Supports {{org}} {{repo}} {{pathname}} placeholders in pattern

## Related Issue

Resolves: GH-244

## Motivation and Context

See the GH issue.

## How Has This Been Tested?

E2E for now. Once approach is agreed upon, will write tests.

## Screenshots (if appropriate):
<img width="655" alt="Screenshot 2024-09-06 at 1 43 20 PM" src="https://github.com/user-attachments/assets/eebbb775-b4fa-4613-ba6c-0361cfbe6bb0">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

2024-09-06 19:47 UTC, auniverseaway commented
I tried to strike a balance between changing _very_ deep parts of Sidekick / Admin and simply bolting on something that cannot be maintained.

My hope is that this can work for XWalk / UE as well.

2024-09-06 20:52 UTC, dylandepass commented on src/extension/app/store/app.js
> +    if (!sourceFormat) return null;
```suggestion
    if (!sourceFormat || typeof sourceFormat.pattern !== 'string') return null;
```

2024-09-06 20:54 UTC, dylandepass commented
Supporting this makes sense to me, and I don’t see any immediate issues with this approach. However, @rofe might have a different perspective. It would also be good to get input from UE to confirm if this works for them.

One suggestion: instead of `sourceFormat`, perhaps something like `contentSourceEditFormat` would be more consistent with related fields like `contentSourceUrl` and `contentSourceType`.

2024-09-07 00:29 UTC, auniverseaway commented
> One suggestion: instead of sourceFormat, perhaps something like contentSourceEditFormat would be more consistent with related fields like contentSourceUrl and contentSourceType.

I changed things to get closer to your comment above. 

**A couple notes:**
1. The patterns exposed in `sidekick/config.json` are less verbose, so I did keep `sourceFormat` as the entry for a project. This should maintain the naming convention style of that file.
2. Putting two top-level properties in `sidekick/config.json` seemed heavy, so I did make `sourceFormat` an object with two properties.
3. Since `contentSourceType` already exists, and is `markup` in these scenarios, I was reluctant to change that property to what is provided by the project. I see `markup` being useful in the long run. 
4. This PR introduces `contentSourceLabel` as the text that is used in the button. SP & GDrive button labels by comparison are calculated based on other details (fstab).
5. This PR introduces `contentSourcePattern` to better match the naming conventions of the project.
6. While the sidekick/config.json is an object with sub-props, I did flatten them down to better fit the style of the codebase. This makes null checks a bit cleaner.

Let me know what y'all think. Happy to adjust further.

The final `sidekick/config.json` looks like:

```json
{
  "project": "DA Block Collection",
  "sourceFormat": {
    "label": "Document Authoring",
    "pattern": "https://da.live/edit#/{{org}}/{{repo}}{{pathname}}"
  }
}
```

2024-09-07 14:05 UTC, rofe requested changes
Looks good in general, but I'm a little concerned that this will be a one-off solution since I'm not sure any of the other BYOM sources will be able provide a pattern containing `org` and `site`...

2024-09-07 14:05 UTC, rofe commented on src/extension/app/store/site.js
> +      sourceFormat,
`contentSourceFormat` or `byomSourceFormat`?

2024-09-07 14:05 UTC, rofe commented on src/extension/app/store/app.js
> +      .replace('{{repo}}', repo)
I would consitently switch from `owner/repo` to `org/site` in all public facing API surfaces.
```suggestion
      .replace('{{site}}', repo)
```

2024-09-07 14:11 UTC, rofe commented
> My hope is that this can work for XWalk / UE as well.

I looked at some existing xwalk mountpoints and it looks like the pattern could be fulfilled. Letting @buuhuu confirm.

2024-09-08 13:24 UTC, rofe commented
Wondering if the label ever need to be localized? If so, you could add an additional, optional `labelI18n` object, analog to the existing `titleI18n` allowing localization of custom button texts in the current schema.

2024-09-09 09:21 UTC, mhaack commented
@rofe @auniverseaway I think this will work with XWalk as well. Today we have a Sidekick overlay which just does 

```
const { pathname } = window.location;
const editorUrl = `${contentSourceUrl}${pathname}?cmd=open`;
```

In the new format this would be 
```
{
  "project": "abc",
  "sourceFormat": {
    "label": "Universal Editor",
    "pattern": "https://author-p1234-e5678.adobeaemcloud.com/bin/franklin.delivery/{{org}}/{{repo}}/main/{{pathname}}?cmd=open"
  }
}
```

2024-09-09 10:53 UTC, buuhuu commented
We should not duplicate the `{{contentSourceUrl}}` if possible, same as we should not duplicate owner, repo, branch. Either we replace all patterns or none. If we say it is fine to duplicate these parameters in the config the proposal would even work without any parameter replacement iiuc.

2024-09-09 16:30 UTC, auniverseaway commented
@buuhuu,
If @rofe approves and it works for you, I think tokenizing `{{contentSourceUrl}}` makes sense. The goal is to put this property in the respective boilerplates and you don't have to change it project to project.

### For an XWalk project, I show:
#### contentSourceUrl
```md
https://author-p15404-e146221-cmstg.adobeaemcloud.com/bin/franklin.delivery/mhaack/my-aem-project/main
```
#### Edit URL
```md
https://author-p15404-e146221-cmstg.adobeaemcloud.com/bin/franklin.delivery/mhaack/my-aem-project/main/index?cmd=open
```
Which means that should work well for UE.

DA / WordPress / Drupal / etc have different content and edit URLs.

2024-09-09 17:40 UTC, buuhuu commented
> The goal is to put this property in the respective boilerplates and you don't have to change it project to project

Can you elaborate on this? With hlx5 repo-less it cannot be in the boilerplate / it changes from project to project.

2024-09-09 18:20 UTC, rofe commented
@buuhuu the reason for supporting variables is that this edit url format can stay fully generic and doesn't need to be changed from project to project.

@auniverseaway I approve :)

2024-09-09 21:03 UTC, auniverseaway commented
I think I accounted for all feedback and suggestions. 

@rofe the only thing I didn't add was `i18n` for the label as it didn't seem like proper nouns would need to be localized: SharePoint, Google Drive, Universal Editor, WordPress, Document Authoring (as a brand name), etc. If you feel strongly we should add the support, let me know.

I modified the original comment with the updated spec, but here it is as well. If I can get thumbs on the final naming conventions I can work on tests and docs.

Thanks!

## Sidekick spec
### UE
```json
{
  "project": "XWalk Block Collection",
  "editUrlFormat": {
    "label": "Universal Editor",
    "pattern": "{{contentSourceUrl}}{{pathname}}?cmd=open"
  }
}
```

### DA
```json
{
  "project": "DA Block Collection",
  "editUrlFormat": {
    "label": "Document Authoring",
    "pattern": "https://da.live/edit#/{{org}}/{{site}}{{pathname}}"
  }
}
```

2024-09-10 09:12 UTC, rofe commented
@auniverseaway we'd also need to update the [config schema](https://www.aem.live/tools/sidekick/config.schema.json). That makes me wonder if it wouldn't be easier to just add 2 top level properies instead of an object?

2024-09-10 15:09 UTC, mhaack commented
Tested it with https://main--my-aem-project--mhaack.aem.page/ for UE & Crosswalks, works nicely. cc @buuhuu

2024-09-18 21:07 UTC, auniverseaway commented
@rofe @dylandepass I think I've got all suggestions covered. I didn't see the schema in the codebase, so my assumption is that it's generated from the TS def?

2024-09-19 13:04 UTC, rofe commented
> I didn't see the schema in the codebase

At the moment, the schema needs to be updated manually here:
https://github.com/adobe/helix-website/blob/main/tools/sidekick/config.schema.json

2024-09-19 13:10 UTC, rofe approved these changes

2024-09-20 04:53 UTC, auniverseaway commented
@rofe updated: https://github.com/adobe/helix-website/pull/657

2024-09-20 07:57 UTC, rofe commented
@auniverseaway I'll merge this into a branch to make sure all checks are passing before mergin to `main`.

2024-09-20 07:59 UTC, merged