feat: Visually align Source in Editor view [env-switcher]
adobe/aem-sidekick pull request #293
Opened 2024-10-01 13:57 UTC by asthabh23

## Description

[env-switcher] visually align "source" item with the others in the popover (along with last modified/edited timestamp)

## Related Issue

Fix #283 

## Screenshots (if appropriate):
**Preview:**
<img width="675" alt="image" src="https://github.com/user-attachments/assets/7ac72e7a-15ca-4792-bff0-879b60047f00">

**Editor:**
<img width="614" alt="image" src="https://github.com/user-attachments/assets/f6c7aa74-e534-4b24-9f27-60b0c152e117">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-10-07 11:02 UTC, rofe commented on src/extension/app/components/plugin/env-switcher/env-switcher.js
> +    const envId = (id === 'dev') ? 'preview' : id;
You can drop the brackets, too

2024-10-07 12:27 UTC, rofe approved these changes

2024-10-07 13:23 UTC, dylandepass requested changes
Very nice @asthabh23 👏🏼

Let's also vertically center the icon
![Screenshot 2024-10-07 at 9 23 06 AM](https://github.com/user-attachments/assets/1a348f1e-b2af-4f90-8a4a-9c9761d2aeab)

2024-10-07 13:23 UTC, dylandepass commented on src/extension/app/components/action-bar/menu-item/menu-item.css.js
> +    background-color: var(--spectrum-gray-200);
```suggestion
    background-color: var(--spectrum2-edit-background-default);
```

2024-10-07 13:23 UTC, dylandepass commented on src/extension/app/components/plugin/env-switcher/env-switcher.js
> +      const descriptionText = currentEnvironment === 'edit'
Could skip the re-assignment and just use `this.currentEnv`

2024-10-07 13:23 UTC, dylandepass commented on test/app/components/plugin/plugin-action-bar.test.js
> +      await sidekickTest.awaitEnvSwitcher();
Could just `awaitEnvSwitcher` if you don't care about the result of `awaitStatusFetched`

2024-10-07 14:41 UTC, dylandepass approved these changes

2024-10-07 15:24 UTC, merged

2024-10-08 08:10 UTC, trieloff commented
:tada: This PR is included in version 2.2.0 :tada:

The release is available on:
- [GitHub release](https://github.com/adobe/aem-sidekick/releases/tag/v2.2.0)
- `v2.2.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: