feat: core plugin support
adobe/aem-sidekick pull request #44
Opened 2024-01-04 19:11 UTC by dylandepass

First draft at plugin support.

Plugins Added

- [x] Environment Switcher
- [x] Edit
- [x] Preview
- [x] Publish

To do

- [ ] Add tests

Not covered in this PR
Custom plugins
Advanced plugins (only visible in advanced mode)
I'm sure there is more...

2024-01-11 01:07 UTC, rofe requested changes

2024-01-19 02:13 UTC, dylandepass commented on src/extension/types/typedefs.js
> + * @prop {boolean} [feature] Determines whether to group this plugin with the features (default: false)
From what I can tell from the designs I don't think there is a "feature" container. Besides the plugin-picker (sorter) and profile button, everything looks to just be "plugins". 

I think we can remove

2024-01-19 02:15 UTC, dylandepass commented on src/extension/types/typedefs.js
> + * @prop {boolean} [override] Determines whether to replace an existing plugin (default: false)
Agreed, can you do complete overrides or just override the condition?

2024-01-19 02:18 UTC, dylandepass commented on src/extension/types/typedefs.js
> + * @prop {ElemConfig[]} [elements]  An array of elements to add (optional)
I'm not seeing anyone using the feature in `adobecom` or `hlxsites`. Are you aware of anyone using it? Curious to see how it's being used.

2024-01-19 02:19 UTC, dylandepass commented on src/extension/types/typedefs.js
> + * @prop {Function} [advanced] Show this plugin only in advanced mode (optional).
Sounds right, will remove

2024-01-19 02:21 UTC, dylandepass commented on src/extension/types/typedefs.js
> + */
I have brought back `createTag` as a shorthand to creating HTMLElements. So I think we still need it.
https://github.com/adobe/aem-sidekick/pull/44/files#diff-706f9ae15c33668b11a311c20ef407c9dec13b61c7d5a9a1ba2e85d7c1b80589R161

2024-01-19 02:30 UTC, dylandepass commented
@rofe In terms of custom events dispatched from plugins.. This maybe tricky to juggle due to the name change of the custom element (helix-sidekick -> aem-sidekick). Guess will have to get people to add event listeners to both elements until `helix-sidekick` is decommisioned.

https://github.com/adobecom/milo/blob/13d29054db249a66b8a257c045d996f7e213c660/libs/utils/sidekick.js#L32

2024-01-19 18:50 UTC, rofe approved these changes

2024-01-19 21:36 UTC, merged

2024-01-19 21:39 UTC, trieloff commented
:tada: This PR is included in version 1.4.0 :tada:

The release is available on [GitHub release](https://github.com/adobe/aem-sidekick/releases/tag/v1.4.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: